## Exercise-1

### 1. Array Computations using NumPy

#### a. Perform arithmetic operations using array

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([5,3,6,7])

In [3]:
"""Addition"""
a+b

array([ 6,  5,  9, 11])

In [4]:
"""Subtraction"""
a-b

array([-4, -1, -3, -3])

In [5]:
"""Multiplication"""
a*b

array([ 5,  6, 18, 28])

In [6]:
"""Division"""
a/b

array([0.2       , 0.66666667, 0.5       , 0.57142857])

In [8]:
"""Exponents of Each Array"""
a**2,b**2

(array([ 1,  4,  9, 16]), array([25,  9, 36, 49]))

In [9]:
a**b

array([    1,     8,   729, 16384])

In [10]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[2, 0], [1, 3]])

# Matrix multiplication (dot product)
matrix_mult_result = np.dot(matrix1, matrix2)
print("Matrix Multiplication:", matrix_mult_result)


Matrix Multiplication: [[ 4  6]
 [10 12]]


#### b. Perform slicing and indexing on multi-dimensional arrays.

In [11]:
# Multidimension arrays
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[3,2,5],[4,2,7]])


In [12]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr2

array([[3, 2, 5],
       [4, 2, 7]])

In [14]:
# Indexing
arr1[0] # Here 0 reperesents 1st row of 2-D Array

array([1, 2, 3])

In [16]:
arr1[0][2] # Here 2 represents 1st row ,last element 0,1,2 index numbers.
arr1[0,2] #We can also represents like this combinely

3

In [18]:
arr1[1,2] #2nd row last element

6

In [24]:
#Slicing
arr3 = np.array([[5,4,7],[3,6,4],[6,8,7]])
arr3

array([[5, 4, 7],
       [3, 6, 4],
       [6, 8, 7]])

In [30]:
row1 = arr3[0,:]
row1 #Gettting First row

array([5, 4, 7])

In [34]:
col1 = arr3[:,1]
col1 #Getting First Column

array([4, 6, 8])

In [39]:
sub_matrix=arr3[0:2,1:3]
#0:2 - it include 0,1 rows 1:3 - it include 1,2 position elements in the given matrix.
sub_matrix 

array([[4, 7],
       [6, 4]])

In [43]:
# Create a 3D array (tensor)
arr4 = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   
                   [[7, 8, 9],
                    [10, 11, 12]]])

# Indexing and slicing in a 3D array
element_3d = arr4[1, 0, 2]  # Tensor[Plane 1, Row 0, Column 2] = 9
plane_0 = arr4[0, :, :]  # First plane (2x3 submatrix)
plane_1_column_1 = arr4[1, :, 1]  # Second plane, all rows, second column
print("Element in 3D array:", element_3d)
print("Plane 0:\n", plane_0)
print("Plane 1, Column 1:", plane_1_column_1)


Element in 3D array: 9
Plane 0:
 [[1 2 3]
 [4 5 6]]
Plane 1, Column 1: [ 8 11]


#### c. Perform computations on multi-dimensional array using universal functions(ufunc).

In [46]:
mat1 = np.array([[4,2,3],[5,2,3],[6,8,4]])

#Adding Scalar to the entire Matrix

mat1 = mat1+10 # 10 is the addition to entire matrix

mat1



array([[14, 12, 13],
       [15, 12, 13],
       [16, 18, 14]])

In [47]:
# Appling square root to entire matrix
squareroot = np.sqrt(mat1)

squareroot

array([[3.74165739, 3.46410162, 3.60555128],
       [3.87298335, 3.46410162, 3.60555128],
       [4.        , 4.24264069, 3.74165739]])

In [48]:
# Appling Exponential to entire matrix

expo = np.exp(mat1)

expo

array([[ 1202604.28416478,   162754.791419  ,   442413.39200892],
       [ 3269017.37247211,   162754.791419  ,   442413.39200892],
       [ 8886110.52050787, 65659969.13733051,  1202604.28416478]])

In [49]:
# applying abs to matrix

abs_mat = np.abs(mat1)

abs_mat

array([[14, 12, 13],
       [15, 12, 13],
       [16, 18, 14]])

#### d. Compute arithmetic mean, standard deviation, variance, percentile, minimum and maximum,cumulative sum and product using statistical functions in NumPy.

In [50]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
arr2

array([[3, 2, 5],
       [4, 2, 7]])

In [52]:
np.mean(arr1)#calculating mean

3.5

In [53]:
np.std(arr1)#calculating standard Deviation

1.707825127659933

In [54]:
np.var(arr2)#calculating variance 

3.1388888888888893

In [57]:
# Percentiles
percentile_25 = np.percentile(arr1, 25)
percentile_50 = np.percentile(arr1, 50)  # Also known as the median
percentile_75 = np.percentile(arr1, 75)
print("25th Percentile:", percentile_25)
print("Median (50th Percentile):", percentile_50)
print("75th Percentile:", percentile_75)

25th Percentile: 2.25
Median (50th Percentile): 3.5
75th Percentile: 4.75


In [58]:
# Minimum and maximum
minimum = np.min(arr1)
maximum = np.max(arr1)
print("Minimum:", minimum)
print("Maximum:", maximum)


Minimum: 1
Maximum: 6


In [60]:
# Cumulative sum and cumulative product
cumulative_sum = np.cumsum(arr1)
cumulative_product = np.cumprod(arr1)
print("Cumulative Sum:", cumulative_sum)
print("Cumulative Product:", cumulative_product)

Cumulative Sum: [ 1  3  6 10 15 21]
Cumulative Product: [  1   2   6  24 120 720]


#### e. Perform set theory operations such as union, intersection, symmetric differenceand fetching unique values.

In [61]:


# Create two arrays for demonstration
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Union
union_result = np.union1d(array1, array2)
print("Union:", union_result)

# Intersection
intersection_result = np.intersect1d(array1, array2)
print("Intersection:", intersection_result)

# Symmetric Difference
symmetric_diff_result = np.setxor1d(array1, array2)
print("Symmetric Difference:", symmetric_diff_result)

# Fetching unique values
unique_values = np.unique(np.concatenate((array1, array2)))
print("Unique Values:", unique_values)


Union: [1 2 3 4 5 6 7]
Intersection: [3 4 5]
Symmetric Difference: [1 2 6 7]
Unique Values: [1 2 3 4 5 6 7]
